unit DmSrv_Intf;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ Do not modify this unit manually, or your changes will be lost when this   }
{ unit is regenerated the next time you compile the project.                 }
{----------------------------------------------------------------------------}

{$I Remobjects.inc}

interface

uses
  {vcl:} Classes, TypInfo,
  {RemObjects:} uROXMLIntf, uROClasses, uROClient, uROTypes, uROClientIntf;

const
  { Library ID }
  LibraryUID = '{F0D2BB67-34F0-4894-AC8F-64989EA28108}';
  TargetNamespace = '';

  { Service Interface ID's }
  ISrvDispensarios_IID : TGUID = '{AAA51A4F-E773-4BFB-9254-9319EBF37DAD}';

  { Event ID's }

type
  { Forward declarations }
  ISrvDispensarios = interface;


  { ISrvDispensarios }
  ISrvDispensarios = interface
    ['{AAA51A4F-E773-4BFB-9254-9319EBF37DAD}']
    function DameDispensarios: String;
    function EjecutaComando(const xCmnd: String): Integer;
    function ResultadoComando(const xFolio: Integer): String;
  end;

  { CoSrvDispensarios }
  CoSrvDispensarios = class
    class function Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): ISrvDispensarios;
  end;

  { TSrvDispensarios_Proxy }
  TSrvDispensarios_Proxy = class(TROProxy, ISrvDispensarios)
  protected
    function __GetInterfaceName:string; override;

    function DameDispensarios: String;
    function EjecutaComando(const xCmnd: String): Integer;
    function ResultadoComando(const xFolio: Integer): String;
  end;

implementation

uses
  {vcl:} SysUtils,
  {RemObjects:} uROEventRepository, uROSerializer, uRORes;

{ CoSrvDispensarios }

class function CoSrvDispensarios.Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): ISrvDispensarios;
begin
  result := TSrvDispensarios_Proxy.Create(aMessage, aTransportChannel);
end;

{ TSrvDispensarios_Proxy }

function TSrvDispensarios_Proxy.__GetInterfaceName:string;
begin
  result := 'SrvDispensarios';
end;

function TSrvDispensarios_Proxy.DameDispensarios: String;
begin
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'DmSrv', __InterfaceName, 'DameDispensarios');
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('Result', TypeInfo(String), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TSrvDispensarios_Proxy.EjecutaComando(const xCmnd: String): Integer;
begin
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'DmSrv', __InterfaceName, 'EjecutaComando');
    __Message.Write('xCmnd', TypeInfo(String), xCmnd, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('Result', TypeInfo(Integer), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

function TSrvDispensarios_Proxy.ResultadoComando(const xFolio: Integer): String;
begin
  try
    __Message.InitializeRequestMessage(__TransportChannel, 'DmSrv', __InterfaceName, 'ResultadoComando');
    __Message.Write('xFolio', TypeInfo(Integer), xFolio, []);
    __Message.Finalize;

    __TransportChannel.Dispatch(__Message);

    __Message.Read('Result', TypeInfo(String), result, []);
  finally
    __Message.UnsetAttributes(__TransportChannel);
    __Message.FreeStream;
  end
end;

initialization
  RegisterProxyClass(ISrvDispensarios_IID, TSrvDispensarios_Proxy);


finalization
  UnregisterProxyClass(ISrvDispensarios_IID);

end.
