unit SrvDispensarios_Impl;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ This is where you are supposed to code the implementation of your objects. }
{----------------------------------------------------------------------------}

{$I Remobjects.inc}

interface

uses
  {vcl:} Classes, SysUtils,
  {RemObjects:} uROXMLIntf, uROClientIntf, uROTypes, uROServer, uROServerIntf, uROSessions,
  {Required:} uRORemoteDataModule,
  {Generated:} DmSrv_Intf;

type
  { TSrvDispensarios }
  TSrvDispensarios = class(TRORemoteDataModule, ISrvDispensarios)
  private
  protected
    { ISrvDispensarios methods }
    function DameDispensarios: String;
    function EjecutaComando(const xCmnd:string):integer;
    function ResultadoComando(const xFolio:integer):string;
  end;

implementation

{$R *.dfm}
uses
  {Generated:} DmSrv_Invk, DDMCONS;

procedure Create_SrvDispensarios(out anInstance : IUnknown);
begin
  anInstance := TSrvDispensarios.Create(nil);
end;

{ SrvDispensarios }
function TSrvDispensarios.DameDispensarios: String;
begin
  result:=DMCONS.ValorDispensarios;
end;

function TSrvDispensarios.EjecutaComando(const xCmnd:string): Integer;
begin
  result:=DMCONS.EjecutaComando(xCmnd);
end;

function TSrvDispensarios.ResultadoComando(const xFolio:integer): String;
begin
  result:=DMCONS.ResultadoComando(xFolio);
end;

initialization
  TROClassFactory.Create('SrvDispensarios', Create_SrvDispensarios, TSrvDispensarios_Invoker);

finalization

end.
